export const GET_LANGUAGES_REQUEST = "GET_LANGUAGES_REQUEST"
export const GET_LANGUAGES_SUCCESS = "GET_LANGUAGES_SUCCESS"
export const GET_LANGUAGES_FAIL = "GET_LANGUAGES_FAIL"


export const GET_SUBMISSIONS_REQUEST = "GET_SUBMISSIONS_REQUEST"
export const GET_SUBMISSIONS_SUCCESS = "GET_SUBMISSIONS_SUCCESS"
export const GET_SUBMISSIONS_FAIL = "GET_SUBMISSIONS_FAIL"

export const GET_TESTCASES_REQUEST = "GET_TESTCASES_REQUEST"
export const GET_TESTCASES_SUCCESS = "GET_TESTCASES_SUCCESS"
export const GET_TESTCASES_FAIL = "GET_TESTCASES_FAIL"

export const GET_BASIC_TESTCASE_REQUEST = "GET_BASIC_TESTCASE_REQUEST"
export const GET_BASIC_TESTCASE_SUCCESS = "GET_BASIC_TESTCASE_SUCCESS"
export const GET_BASIC_TESTCASE_FAIL = "GET_BASIC_TESTCASE_FAIL"

export const CREATE_NEW_SUBMISSION_REQUEST = "CREATE_NEW_SUBMISSION_REQUEST"
export const CREATE_NEW_SUBMISSION_SUCCESS = "CREATE_NEW_SUBMISSION_SUCCESS"
export const CREATE_NEW_SUBMISSION_FAIL = "CREATE_NEW_SUBMISSION_FAIL"

export const GET_ALGO_QUESTIONS ={
    REQUEST:"GET_ALGO_QUESTIONS_REQUEST",
    SUCCESS:"GET_ALGO_QUESTIONS_SUCCESS",
    FAIL:"GET_ALGO_QUESTIONS_FAIL"
}

export const GET_TIPS={
    REQUEST:"GET_TIPS_REQUEST",
    SUCCESS:"GET_TIPS_SUCCESS",
    FAIL:"GET_TIPS_FAIL"
}
