export const GET_LANGUAGES_REQUEST = "GET_LANGUAGES_REQUEST"
export const GET_LANGUAGES_SUCCESS = "GET_LANGUAGES_SUCCESS"
export const GET_LANGUAGES_FAIL = "GET_LANGUAGES_FAIL"


export const GET_SUBMISSIONS_REQUEST = "GET_SUBMISSIONS_REQUEST"
export const GET_SUBMISSIONS_SUCCESS = "GET_SUBMISSIONS_SUCCESS"
export const GET_SUBMISSIONS_FAIL = "GET_SUBMISSIONS_FAIL"