
export const GET_DOCUMENTATION_BY_ID = {
    REQUEST : "GET_DOCUMENTATION_BY_ID_REQUEST",
    SUCCESS : "GET_DOCUMENTATION_BY_ID_SUCCESS",
    FAIL : "GET_DOCUMENTATION_BY_ID_FAIL"
}

export const GET_CHATTING_QUESTIONS = {
    REQUEST : "GET_CHATTING_QUESTIONS_REQUEST",
    SUCCESS : "GET_CHATTING_QUESTIONS_SUCCESS",
    FAIL : "GET_CHATTING_QUESTIONS_FAIL"
}

export const GET_CHATTING_QUESTION_ANSWER = {
    REQUEST : "GET_CHATTING_QUESTION_ANSWER_REQUEST",
    SUCCESS : "GET_CHATTING_QUESTION_ANSWER_SUCCESS",
    FAIL : "GET_CHATTING_QUESTION_ANSWER_FAIL"
}