export const REMOVE_POINTS_REQUEST = "REMOVE_POINTS_REQUEST"
export const REMOVE_POINTS_SUCCESS = "REMOVE_POINTS_SUCCESS"
export const REMOVE_POINTS_FAIL = "REMOVE_POINTS_FAIL"


export const ADD_POINTS_REQUEST = "ADD_POINTS_REQUEST"
export const ADD_POINTS_SUCCESS = "ADD_POINTS_SUCCESS"
export const ADD_POINTS_FAIL = "ADD_POINTS_FAIL"
export const REDIRECT_REQUIRED = "REDIRECT_REQUIRED"

export const GET_USER_CURRENT_QUIZ_BAD_ANSWERS = {
    "REQUEST" : "GET_USER_CURRENT_QUIZ_BAD_ANSWERS_REQUEST",
    "FAIL" : "GET_USER_CURRENT_QUIZ_BAD_ANSWERS_FAIL",
    "SUCCESS" : "GET_USER_CURRENT_QUIZ_BAD_ANSWERS_SUCCESS",

}