export const ROADMAP_GETALL_REQUEST = "ROADMAP_GETALL_REQUEST"
export const ROADMAP_GETALL_SUCCESS = "ROADMAP_GETALL_SUCCESS"
export const ROADMAP_GETALL_FAIL = "ROADMAP_GETALL_FAIL"
export const ROADMAP_GETALL_RESET = "ROADMAP_GETALL_RESET"


export const ROADMAP_REQUEST = "ROADMAP_REQUEST"
export const ROADMAP_SUCCESS = "ROADMAP_SUCCESS"
export const ROADMAP_FAIL= "ROADMAP_FAIL"
export const ROADMAP_RESET="ROADMAP_RESET"

export const SCHEDULE_TIME_REQUEST = "SCHEDULE_TIME_REQUEST"
export const SCHEDULE_TIME_SUCCESS = "SCHEDULE_TIME_SUCCESS"
export const SCHEDULE_TIME_FAIL = "SCHEDULE_TIME_FAIL"

export const GET_AVAILABLE_ROADMAPS_REQUEST = "GET_AVAILABLE_ROADMAPS_REQUEST"
export const GET_AVAILABLE_ROADMAPS_SUCCESS = "GET_AVAILABLE_ROADMAPS_SUCCESS"
export const GET_AVAILABLE_ROADMAPS_FAIL = "GET_AVAILABLE_ROADMAPS_FAIL"

export const GET_COINS_YOU_MISS_TO_SKIP={
    REQUEST:"GET_COINS_YOU_MISS_TO_SKIP_REQUEST",
    SUCCESS:"GET_COINS_YOU_MISS_TO_SKIP_SUCCESS",
    FAIL:"GET_COINS_YOU_MISS_TO_SKIP_FAIL"
}

export const HANDLE_DELETING_COINS_YOU_MISS_TO_SKIP={
    REQUEST:"HANDLE_DELETING_COINS_YOU_MISS_TO_SKIP_REQUEST",
    SUCCESS:"HANDLE_DELETING_COINS_YOU_MISS_TO_SKIP_SUCCESS",
    FAIL:"HANDLE_DELETING_COINS_YOU_MISS_TO_SKIP_FAIL"
}