export const ROADMAP_GETALL_REQUEST = "ROADMAP_GETALL_REQUEST"
export const ROADMAP_GETALL_SUCCESS = "ROADMAP_GETALL_SUCCESS"
export const ROADMAP_GETALL_FAIL = "ROADMAP_GETALL_FAIL"
export const ROADMAP_GETALL_RESET = "ROADMAP_GETALL_RESET"


export const ROADMAP_REQUEST = "ROADMAP_REQUEST"
export const ROADMAP_SUCCESS = "ROADMAP_SUCCESS"
export const ROADMAP_FAIL= "ROADMAP_FAIL"
export const ROADMAP_RESET="ROADMAP_RESET"