

export const USER_REGISTER_NEWS_LETTER_REQUEST = "USER_REGISTER_NEWS_LETTER_REQUEST"
export const USER_REGISTER_NEWS_LETTER_SUCCESS = "USER_REGISTER_NEWS_LETTER_SUCCESS"
export const USER_REGISTER_NEWS_LETTER_FAIL = "USER_REGISTER_NEWS_LETTER_FAIL"


export const USER_SEND_EMAIL_REQUEST = "USER_SEND_EMAIL_REQUEST"
export const USER_SEND_EMAIL_SUCCESS = "USER_SEND_EMAIL_SUCCESS"
export const USER_SEND_EMAIL_FAIL = "USER_SEND_EMAIL_FAIL"
export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";

export const USER_LIKE = {
    REQUEST: "USER_LIKE_REQUEST",
    SUCCESS: "USER_LIKE_SUCCESS",
    FAIL: "USER_LIKE_FAIL"
}

export const USER_DISLIKE = {
    REQUEST: "USER_DISLIKE_REQUEST",
    SUCCESS: "USER_DISLIKE_SUCCESS",
    FAIL: "USER_DISLIKE_FAIL"
}

export const USER_DIFFICULTY = {
    REQUEST : "USER_DIFFICULTY_REQUEST",
    SUCCESS : "USER_DIFFICULTY_SUCCESS",
    FAIL : "USER_DIFFICULTY_FAIL"
}

export const USER_REVIEW = {
    REQUEST : "USER_REVIEW_REQUEST",
    SUCCESS : "USER_REVIEW_SUCCESS",
    FAIL : "USER_REVIEW_FAIL"
}

export const USER_PROPOSE_ALGORITHM = {
    REQUEST : "USER_PROPOSE_ALGORITHM_REQUEST",
    SUCCESS : "USER_PROPOSE_ALGORITHM_SUCCESS",
    FAIL : "USER_PROPOSE_ALGORITHM_FAIL"
}