export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST"
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS"
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL"


export const USER_REGISTER_NEWS_LETTER_REQUEST = "USER_REGISTER_NEWS_LETTER_REQUEST"
export const USER_REGISTER_NEWS_LETTER_SUCCESS = "USER_REGISTER_NEWS_LETTER_SUCCESS"
export const USER_REGISTER_NEWS_LETTER_FAIL = "USER_REGISTER_NEWS_LETTER_FAIL"


export const USER_SEND_EMAIL_REQUEST = ":USER_SEND_EMAIL_REQUEST"
export const USER_SEND_EMAIL_SUCCESS = ":USER_SEND_EMAIL_SUCCESS"
export const USER_SEND_EMAIL_FAIL = ":USER_SEND_EMAIL_FAIL"