

export const USER_REGISTER_NEWS_LETTER_REQUEST = "USER_REGISTER_NEWS_LETTER_REQUEST"
export const USER_REGISTER_NEWS_LETTER_SUCCESS = "USER_REGISTER_NEWS_LETTER_SUCCESS"
export const USER_REGISTER_NEWS_LETTER_FAIL = "USER_REGISTER_NEWS_LETTER_FAIL"


export const USER_SEND_EMAIL_REQUEST = "USER_SEND_EMAIL_REQUEST"
export const USER_SEND_EMAIL_SUCCESS = "USER_SEND_EMAIL_SUCCESS"
export const USER_SEND_EMAIL_FAIL = "USER_SEND_EMAIL_FAIL"
export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";

export const USER_LIKE = {
    REQUEST: "USER_LIKE_REQUEST",
    SUCCESS: "USER_LIKE_SUCCESS",
    FAIL: "USER_LIKE_FAIL"
}

export const USER_DISLIKE = {
    REQUEST: "USER_DISLIKE_REQUEST",
    SUCCESS: "USER_DISLIKE_SUCCESS",
    FAIL: "USER_DISLIKE_FAIL"
}

export const USER_DIFFICULTY = {
    REQUEST : "USER_DIFFICULTY_REQUEST",
    SUCCESS : "USER_DIFFICULTY_SUCCESS",
    FAIL : "USER_DIFFICULTY_FAIL"
}

export const USER_REVIEW = {
    REQUEST : "USER_REVIEW_REQUEST",
    SUCCESS : "USER_REVIEW_SUCCESS",
    FAIL : "USER_REVIEW_FAIL"
}

export const USER_PROPOSE_ALGORITHM = {
    REQUEST : "USER_PROPOSE_ALGORITHM_REQUEST",
    SUCCESS : "USER_PROPOSE_ALGORITHM_SUCCESS",
    FAIL : "USER_PROPOSE_ALGORITHM_FAIL"
}

export const GET_USER_SUBMISSION_RESULT_BY_ID = {
    REQUEST : "GET_USER_SUBMISSION_RESULT_BY_ID_REQUEST",
    SUCCESS : "GET_USER_SUBMISSION_RESULT_BY_ID_SUCCESS",
    FAIL : "GET_USER_SUBMISSION_RESULT_BY_ID_FAIL",
}

export const USER_CREATES_ALGO_QUESTION = {
    REQUEST  : "USER_CREATES_ALGO_QUESTION_REQUEST",
    SUCCESS : "USER_CREATES_ALGO_QUESTION_SUCCESS",
    FAIL : "USER_CREATES_ALGO_QUESTION_FAIL"
}

export const USER_ENTITIE_DISLIKE = {
    REQUEST : "USER_ENTITIE_DISLIKE_REQUEST",
    SUCCESS :"USER_ENTITIE_DISLIKE_SUCCESS",
    FAIL:"USER_ENTITIE_DISLIKE_FAIL"
}

export const USER_ENTITIE_UNDO_LIKE = {
    REQUEST : "USER_ENTITIE_UNDO_LIKE_REQUEST",
    SUCCESS : "USER_ENTITIE_UNDO_LIKE_SUCCESS",
    FAIL : "USER_ENTITIE_UNDO_LIKE_FAIL"
}

export const USER_ENTITIE_UNDO_DISLIKE = {
    REQUEST : "USER_ENTITIE_UNDO_DISLIKE_REQUEST",
    SUCCESS : "USER_ENTITIE_UNDO_DISLIKE_SUCCESS",
    FAIL : "USER_ENTITIE_UNDO_DISLIKE_FAIL"
}

export const USER_CREATE_ALGO_QUESTION_COMMENT = {
    REQUEST : "USER_CREATE_ALGO_QUESTION_COMMENT_REQUEST",
    SUCCESS : "USER_CREATE_ALGO_QUESTION_COMMENT_SUCCESS",
    FAIL : "USER_CREATE_ALGO_QUESTION_COMMENT_FAIL"
}

export const GET_ALGO_QUESTION_COMMENTS = {
    REQUEST : "GET_ALGO_QUESTION_COMMENTS_REQUEST",
    SUCCESS : "GET_ALGO_QUESTION_COMMENTS_SUCCESS" , 
    FAIL : "GET_ALGO_QUESTION_COMMENTS_FAIL"
}

export const USER_PROPOSE_ALGO_SOLUTION = {
    REQUEST : "USER_PROPOSE_ALGO_SOLUTION_REQUEST",
    SUCCESS : "USER_PROPOSE_ALGO_SOLUTION_SUCCESS",
    FAIL : 'USER_PROPOSE_ALGO_SOLUTION_FAIL'
}

export const USER_GET_PROFILE_DATA = {
    REQUEST : "USER_GET_PROFILE_DATA_REQUEST",
    SUCCESS : "USER_GET_PROFILE_DATA_SUCCESS",
    FAIL : "USER_GET_PROFILE_DATA_FAIL"
}

export const USER_PROFILE_ROADMAP_CHAPTER_DATA = {
    REQUEST : "USER_PROFILE_ROADMAP_CHAPTER_DATA_REQUEST",
    SUCCESS : "USER_PROFILE_ROADMAP_CHAPTER_DATA_SUCCESS",
    FAIL : "USER_PROFILE_ROADMAP_CHAPTER_DATA_FAIL"
}

export const USER_PROFILE_INFO = {
    REQUEST : "USER_PROFILE_INFO_REQUEST",
    SUCCESS : "USER_PROFILE_INFO_SUCCESS",
    FAIL : "USER_PROFILE_INFO_FAIL"
}