export const GET_WRITTEN_COURSE = {
    REQUEST : 'GET_WRITTEN_COURSES_REQUEST',
    SUCCESS : 'GET_WRITTEN_COURSES_SUCCESS',
    FAIL : 'GET_WRITTEN_COURSES_FAIL'
}

export const GET_WRITTEN_COURSE_BY_ID = {
    REQUEST : "GET_WRITTEN_COURSE_BY_ID_REQUEST",
    SUCCESS : "GET_WRITTEN_COURSE_BY_ID_SUCCESS",
    FAIL : "GET_WRITTEN_COURSE_BY_ID_FAIL"
}

export const GET_USER_WRITTEN_COURSE = {
    REQUEST : "GET_USER_WRITTEN_COURSE_REQUEST",
    SUCCESS: "GET_USER_WRITTEN_COURSE_SUCCESS",
    FAIL : "GET_USER_WRITTEN_COURSE_FAIL"
}

export const UPDATE_AND_RETRIEVE_USER_WRITTEN_COURSE = {
    REQUEST : "UPDATE_AND_RETREIVE_USER_WRITTEN_COURSE_REQUEST",
    SUCCESS : "UPDATE_AND_RETREIVE_USER_WRITTEN_COURSE_SUCCESS",
    FAIL : "UPDATE_AND_RETREIVE_USER_WRITTEN_COURSE_FAIL"
}

export const UPDATE_USER_WRITTEN_COURSE_BACKUP = {
    REQUEST : "UPDATE_USER_WRITTEN_COURSE_BACKUP_REQUEST",
    SUCCESS : "UPDATE_USER_WRITTEN_COURSE_BACKUP_SUCCESS",
    FAIL : "UPDATE_USER_WRITTEN_COURSE_BACKUP_FAIL"
}

export const RUN_WRITTEN_COURSE_CODE = {
    REQUEST : "RUN_WRITTEN_COURSE_CODE_REQUEST",
    SUCCESS : "RUN_WRITTEN_COURSE_CODE_SUCCESS",
    FAIL : "RUN_WRITTEN_COURSE_CODE_FAIL"
}